In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

import math

#import torchtext

import datasets

from tqdm import tqdm

C:\Users\raviv\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [4]:
#pip install datasets

In [5]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
torch.manual_seed(0)

In [9]:
### Load the Dataset
dataset = datasets.load_dataset('wikitext', 'wikitext-2-raw-v1')
#print(dataset)
print(dataset['train'][88]['text'])

 This ammunition , and that which I brought with me , was rapidly prepared for use at the Laboratory established at the Little Rock Arsenal for that purpose . As illustrating as the pitiful scarcity of material in the country , the fact may be stated that it was found necessary to use public documents of the State Library for cartridge paper . Gunsmiths were employed or conscripted , tools purchased or impressed , and the repair of the damaged guns I brought with me and about an equal number found at Little Rock commenced at once . But , after inspecting the work and observing the spirit of the men I decided that a garrison 500 strong could hold out against Fitch and that I would lead the remainder - about 1500 - to Gen 'l Rust as soon as shotguns and rifles could be obtained from Little Rock instead of pikes and lances , with which most of them were armed . Two days elapsed before the change could be effected . " 



In [2]:
caches = [[] for _ in range(2)]

In [3]:
caches

[[], []]

In [4]:
len(caches[0])

0

In [5]:
for t in range(5):
    for layer in range(2):
        caches[layer].append(5)

In [6]:
caches

[[5, 5, 5, 5, 5], [5, 5, 5, 5, 5]]

In [8]:
len(caches[0])

5

In [2]:
import numpy as np

In [9]:
a=np.ones((1,4))

In [10]:
b=np.ones((4,1))

In [11]:
c=np.dot(a,b)

In [12]:
c

array([[4.]])

In [13]:
a

array([[1., 1., 1., 1.]])

In [14]:
b

array([[1.],
       [1.],
       [1.],
       [1.]])

In [15]:
a.shape

(1, 4)

In [16]:
b.shape

(4, 1)

In [17]:
!wget http://srecord.sourceforge.net/srecord-1.64.tar.gz


'wget' is not recognized as an internal or external command,
operable program or batch file.
